// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20210107231646_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<int>("Rating");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Portland",
                            Country = "USA",
                            Rating = 3,
                            UserName = "Pat Benatar"
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "Moskow",
                            Country = "Russia",
                            Rating = 4,
                            UserName = "Pat Benatar"
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Sydney",
                            Country = "Australia",
                            Rating = 5,
                            UserName = "Yolo Banksy"
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Sydney",
                            Country = "Australia",
                            Rating = 5,
                            UserName = "Kate Austen"
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Sydney",
                            Country = "Australia",
                            Rating = 5,
                            UserName = "Kaitlinn Bennet"
                        },
                        new
                        {
                            ReviewId = 6,
                            City = "Sydney",
                            Country = "Australia",
                            Rating = 5,
                            UserName = "Hosia"
                        },
                        new
                        {
                            ReviewId = 7,
                            City = "Sydney",
                            Country = "Australia",
                            Rating = 5,
                            UserName = "Charlie Bonkadonk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
