// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    partial class TravelAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("Rating");

                    b.Property<string>("UserName");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Portland",
                            Country = "USA",
                            Rating = 3,
                            UserName = "Pat Benatar"
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "Moskow",
                            Country = "Russia",
                            Rating = 4,
                            UserName = "Pat Benatar"
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Sydney",
                            Country = "Australia",
                            Rating = 5,
                            UserName = "Charles Barkely"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
